# Generated by Django 5.2 on 2025-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_file_unique_together_file_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
