# Generated by Django 5.2 on 2025-07-31 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_sys_app', '0003_filechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.CharField(max_length=100, unique=True)),
                ('github_owner', models.CharField(max_length=100)),
                ('github_name', models.CharField(max_length=100)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('clone_url', models.URLField()),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='file_sys_app.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'github_repo_id')},
            },
        ),
    ]
