# Generated by Django 5.2 on 2025-08-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys_app', '0003_filechange'),
        ('git_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='file_sys_app.folder'),
        ),
    ]
