# Generated by Django 5.2 on 2025-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='exec_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='last_compiled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
