# Generated by Django 5.2 on 2025-07-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys_app', '0002_folder_exec_file_folder_last_compiled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('insert', 'Insert'), ('delete', 'Delete')], max_length=10)),
                ('position', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='file_sys_app.file')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
