# Generated by Django 5.2 on 2025-08-04 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sys_app', '0003_filechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('extension', models.CharField(blank=True, max_length=15, null=True)),
                ('is_executable', models.BooleanField(default=False)),
                ('is_symlink', models.BooleanField(default=False)),
                ('symlink_target', models.CharField(blank=True, max_length=500, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_files', to='file_sys_app.folder')),
            ],
            options={
                'indexes': [models.Index(fields=['folder', 'file_name'], name='file_sys_ap_folder__5251aa_idx')],
                'unique_together': {('folder', 'file_name', 'extension')},
            },
        ),
    ]
